version: '2'

networks:
  app-tier:
    driver: bridge

services:
  
  # kafka-stream-app:
  #   build:
  #     context: .
  #     dockerfile: defi-tweet-stream/Dockerfile
  #   # environment:
  #   #   ADV_HOST: 127.0.0.1         
  #   #   RUNTESTS: 0            
  #   # ports:
  #   #   - "9200:9200"
  #   #     - 2181:2181  
  #   networks:
  #     - app-tier    
        
  kafka-cluster:
    image: landoop/fast-data-dev:cp3.3.0
    networks:
      - app-tier
    environment:
      ADV_HOST: 127.0.0.1         
      RUNTESTS: 0                 
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
    volumes:
      - ./docker-mount:/app

  elasticsearch:
    image: itzg/elasticsearch:2.4.3
    networks:
      - app-tier
    environment:
      PLUGINS: appbaseio/dejavu
      OPTS: -Dindex.number_of_shards=1 -Dindex.number_of_replicas=0
    ports:
      - "9200:9200"

 
  postgres:
    image: postgres:9.5-alpine
    networks:
      - app-tier
    environment:
      POSTGRES_USER: postgres     
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: postgres       
    ports:
      - 5432:5432                 
